config/routes.rb
Rails.application.routes.draw do
  resources :credit_charges

  resources :customers

   root 'credit_charges#index'

end

app/models/credit_charge.rb
class CreditCharge < ActiveRecord::Base

	belongs_to :customer
	delegate :first_name, :last_name, to: :customer, prefix: true

	THEAD = ['Customer Name', 'Amount', 'Date']

	scope :status, ->(state){ where(define_status(state))}

	def self.define_status type
		cond = nil
		case type.downcase
		when 'failed'
			cond = {paid: true, refunded: true}
		when 'disputed'
			cond = {paid: true, disputed: true}
		when 'successful'
			cond = {paid: true, disputed: false, refunded: false}
		end
		cond
	end
end

app/models/customer.rb
class Customer < ActiveRecord::Base

	has_many :credit_charges

	def name
		"#{first_name} #{last_name}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/credit_charges_controller.rb
class CreditChargesController < ApplicationController
  before_action :set_credit_charge, only: [:show, :edit, :update, :destroy]

  # GET /credit_charges
  # GET /credit_charges.json
  def index
    @credit_charges = CreditCharge.includes(:customer).all
  end

  # GET /credit_charges/1
  # GET /credit_charges/1.json
  def show
  end

  # GET /credit_charges/new
  def new
    @credit_charge = CreditCharge.new
  end

  # GET /credit_charges/1/edit
  def edit
  end

  # POST /credit_charges
  # POST /credit_charges.json
  def create
    @credit_charge = CreditCharge.new(credit_charge_params)

    respond_to do |format|
      if @credit_charge.save
        format.html { redirect_to @credit_charge, notice: 'Credit charge was successfully created.' }
        format.json { render :show, status: :created, location: @credit_charge }
      else
        format.html { render :new }
        format.json { render json: @credit_charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_charges/1
  # PATCH/PUT /credit_charges/1.json
  def update
    respond_to do |format|
      if @credit_charge.update(credit_charge_params)
        format.html { redirect_to @credit_charge, notice: 'Credit charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_charge }
      else
        format.html { render :edit }
        format.json { render json: @credit_charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_charges/1
  # DELETE /credit_charges/1.json
  def destroy
    @credit_charge.destroy
    respond_to do |format|
      format.html { redirect_to credit_charges_url, notice: 'Credit charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_charge
      @credit_charge = CreditCharge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_charge_params
      params.require(:credit_charge).permit(:paid, :amount, :created, :currency, :refunded, :customer_id, :disputed)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def table records, options={}
		table = "<table id='#{options[:type] || 'successful'}'>"
		table += th records
		table += tbody records, options[:type] || 'successful'
		table += '</table>'
		table.html_safe
	end

	def th records, thead = ''
		columns = columns records	
		columns.each_with_index do |th,i,zero=0|
			thead = "<thead><tr>" if i.eql? zero
			thead += "<th>#{th}</th>"
			thead += "</tr></thead>" if (i+1).eql? columns.length 
		end
		thead
	end

	def tbody records, type, tbody='', tds=''
		tbody = "<tr><td colspan = '#{columns(records).length}'>No Data</td></tr>"
		records.each_with_index do |record,i,zero=0|
			tds.send "#{i.eql?(zero) ? 'replace' : 'concat'}", "<tr class = #{type.downcase}>"
			tds += row(record)
			tds += "</tr>"
		end
		"<tbody>#{tds}</tbody>"
	end

	def columns records
		eval "#{records.klass.name}::THEAD"	rescue []
	end

end

app/helpers/credit_charges_helper.rb
module CreditChargesHelper

	def row charge
		td = "<td> #{charge.customer.name rescue ''} </td>"
		td += "<td> #{charge.currency.upcase rescue 'IDR'} #{charge.amount} </td>"
		td += "<td> #{Time.at(charge.created).to_date.strftime '%d %B %Y'} </td>"			
	end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/credit_charges/_form.html.erb
<%= form_for(@credit_charge) do |f| %>
  <% if @credit_charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_charge.errors.count, "error") %> prohibited this credit_charge from being saved:</h2>

      <ul>
      <% @credit_charge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :paid %><br>
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :created %><br>
    <%= f.number_field :created %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :refunded %><br>
    <%= f.check_box :refunded %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :disputed %><br>
    <%= f.check_box :disputed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_charges/edit.html.erb
<h1>Editing credit_charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_charge %> |
<%= link_to 'Back', credit_charges_path %>

app/views/credit_charges/index.html.erb
<h1>Failed Charges</h1>

  <%=table @credit_charges.status('failed'), {type: 'failed'}%>

<h1>Disputed Charges</h1>
  
  <%=table @credit_charges.status('disputed'), {type: 'disputed'}%>

<h1>Succesful Charge</h1>

  <%=table @credit_charges.status('successful'), refunded: false%>  

app/views/credit_charges/new.html.erb
<h1>New credit_charge</h1>

<%= render 'form' %>

<%= link_to 'Back', credit_charges_path %>

app/views/credit_charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paid:</strong>
  <%= @credit_charge.paid %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @credit_charge.amount %>
</p>

<p>
  <strong>Created:</strong>
  <%= @credit_charge.created %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @credit_charge.currency %>
</p>

<p>
  <strong>Refunded:</strong>
  <%= @credit_charge.refunded %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @credit_charge.customer_id %>
</p>

<p>
  <strong>Disputed:</strong>
  <%= @credit_charge.disputed %>
</p>

<%= link_to 'Edit', edit_credit_charge_path(@credit_charge) %> |
<%= link_to 'Back', credit_charges_path %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestKubiko</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>